#!/bin/python3
import time
import random
import RPi.GPIO as GPIO

TIME=0.05
SEQ=(1,1,1,1,1,1,1,1,1,1,1,1,1,100,100,1)

GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False);

GPIO.setup(2, GPIO.OUT)
#GPIO.setup(3, GPIO.OUT)
GPIO.setup(4, GPIO.OUT)
GPIO.setup(5, GPIO.OUT)
GPIO.setup(6, GPIO.OUT)
GPIO.setup(7, GPIO.OUT)
GPIO.setup(8, GPIO.OUT)
GPIO.setup(9, GPIO.OUT)
GPIO.setup(10, GPIO.OUT)
GPIO.setup(11, GPIO.OUT)
GPIO.setup(12, GPIO.OUT)
GPIO.setup(13, GPIO.OUT)
GPIO.setup(14, GPIO.OUT)
GPIO.setup(15, GPIO.OUT)
GPIO.setup(16, GPIO.OUT)
GPIO.setup(17, GPIO.OUT)
GPIO.setup(18, GPIO.OUT)
GPIO.setup(19, GPIO.OUT)
GPIO.setup(20, GPIO.OUT)
GPIO.setup(21, GPIO.OUT)
GPIO.setup(22, GPIO.OUT)
GPIO.setup(23, GPIO.OUT)
GPIO.setup(24, GPIO.OUT)
GPIO.setup(25, GPIO.OUT)
GPIO.setup(26, GPIO.OUT)
GPIO.setup(27, GPIO.OUT)


p02 = GPIO.PWM( 2, 50)  # channel=12 frequency=50Hz
p04 = GPIO.PWM( 4, 50)
p05 = GPIO.PWM( 5, 50)
p06 = GPIO.PWM( 6, 50)
p07 = GPIO.PWM( 7, 50)
p08 = GPIO.PWM( 8, 50)
p09 = GPIO.PWM( 9, 50)
p10 = GPIO.PWM(10, 50)
p11 = GPIO.PWM(11, 50)
p12 = GPIO.PWM(12, 50)
p13 = GPIO.PWM(13, 50)
p14 = GPIO.PWM(14, 50)
p15 = GPIO.PWM(15, 50)
p16 = GPIO.PWM(16, 50)
p17 = GPIO.PWM(17, 50)
p18 = GPIO.PWM(18, 50)
p19 = GPIO.PWM(19, 50)
p20 = GPIO.PWM(20, 50)
p21 = GPIO.PWM(21, 50)
p22 = GPIO.PWM(22, 50)
p23 = GPIO.PWM(23, 50)
p24 = GPIO.PWM(24, 50)
p25 = GPIO.PWM(25, 50)
p26 = GPIO.PWM(26, 50)
p27 = GPIO.PWM(27, 50)

p02.start(0)
p04.start(0)
p05.start(0)
p06.start(0)
p07.start(0)
p08.start(0)
p09.start(0)
p10.start(0)
p11.start(0)
p12.start(0)
p13.start(0)
p14.start(0)
p15.start(0)
p16.start(0)
p17.start(0)
p18.start(0)
p19.start(0)
p20.start(0)
p21.start(0)
p22.start(0)
p23.start(0)
p24.start(0)
p25.start(0)
p26.start(0)
p27.start(0)




try:
    while 1:
#        for dc in range(0, 100, 5):
            dc=random.choice(SEQ)
            p02.ChangeDutyCycle(dc)
            dc=random.choice(SEQ)
            p04.ChangeDutyCycle(dc)
            dc=random.choice(SEQ)
            p05.ChangeDutyCycle(dc)
            dc=random.choice(SEQ)
            p06.ChangeDutyCycle(dc)
            dc=random.choice(SEQ)
            p07.ChangeDutyCycle(dc)
            dc=random.choice(SEQ)
            p08.ChangeDutyCycle(dc)
            dc=random.choice(SEQ)
            p09.ChangeDutyCycle(dc)
            dc=random.choice(SEQ)
            p10.ChangeDutyCycle(dc)
            dc=random.choice(SEQ)
            p11.ChangeDutyCycle(dc)
            dc=random.choice(SEQ)
            p12.ChangeDutyCycle(dc)
            dc=random.choice(SEQ)
            p13.ChangeDutyCycle(dc)
            dc=random.choice(SEQ)
            p14.ChangeDutyCycle(dc)
            dc=random.choice(SEQ)
            p15.ChangeDutyCycle(dc)
            dc=random.choice(SEQ)
            p16.ChangeDutyCycle(dc)
            dc=random.choice(SEQ)
            p17.ChangeDutyCycle(dc)
            dc=random.choice(SEQ)
            p18.ChangeDutyCycle(dc)
            dc=random.choice(SEQ)
            p19.ChangeDutyCycle(dc)
            dc=random.choice(SEQ)
            p20.ChangeDutyCycle(dc)
            dc=random.choice(SEQ)
            p21.ChangeDutyCycle(dc)
            dc=random.choice(SEQ)
            p22.ChangeDutyCycle(dc)
            dc=random.choice(SEQ)
            p23.ChangeDutyCycle(dc)
            dc=random.choice(SEQ)
            p24.ChangeDutyCycle(dc)
            dc=random.choice(SEQ)
            p25.ChangeDutyCycle(dc)
            dc=random.choice(SEQ)
            p26.ChangeDutyCycle(dc)
            dc=random.choice(SEQ)
            p27.ChangeDutyCycle(dc)


            time.sleep(TIME)

except KeyboardInterrupt:
    pass
#p.stop()
GPIO.cleanup()
